run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - gosimple
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/bellanov/golang-samples

issues:
  exclude-generics: true
